Meet Add-ons web sample
googleworkspace/meet pull request #8
Opened 2024-08-06 17:29 UTC by GGG-eee

Meet Add-ons web tutorial sample code.

2024-08-06 19:50 UTC, benediktbrandt requested changes
Did a first pass and left some questions. Will do another pass once those are addressed. 

In general there seems to be some code in here that is representing defaults / seems to be unused. We should make sure to trim this down so that it is as simple as possible.

2024-08-06 19:50 UTC, benediktbrandt commented on meet-addons-web-tutorial/firestore.rules
> +			function isCollaborator(rsc) {
indent seems off

2024-08-06 19:50 UTC, benediktbrandt commented on meet-addons-web-tutorial/firestore.rules
> +			function isWriter(rsc) {
indent seems off

2024-08-06 19:50 UTC, benediktbrandt commented on meet-addons-web-tutorial/firestore.rules
> +	  match /tasks/{task} {
indent seems off

2024-08-06 19:50 UTC, benediktbrandt commented on meet-addons-web-tutorial/src/app/meet/layout.tsx
> +        src="https://www.gstatic.com/meetjs/addons/0.1.0/meet.addons.js"
please update to the latest version

2024-08-06 19:50 UTC, benediktbrandt commented on meet-addons-web-tutorial/src/app/page.tsx
> +"use client";
when would this page be used?

2024-08-06 19:50 UTC, benediktbrandt commented on meet-addons-web-tutorial/src/app/page.tsx
> +"use client";
Isn't the user always interacting with meet-addons-web-tutorial/src/app/meet/sidepanel/page.tsx?

2024-08-06 19:50 UTC, benediktbrandt commented on meet-addons-web-tutorial/postcss.config.js
seems like this file is empty. Is it needed?

2024-08-06 19:50 UTC, benediktbrandt commented on meet-addons-web-tutorial/src/app/globals.css
> +    font-weight: normal;
Here and in other places. I believe those are the defaults. Do we need to specify them here?

2024-08-06 19:50 UTC, benediktbrandt commented on meet-addons-web-tutorial/tailwind.config.ts
> +  theme: {
this seems empty do we need it?

2024-08-06 19:50 UTC, benediktbrandt commented on meet-addons-web-tutorial/src/app/layout.tsx
> +        <Script src="https://www.gstatic.com/meetjs/addons/latest/meet.addons.screenshare.js"></Script>
I am not sure I follow why we are importing the screenshare sdk here. Can you explain what the intent is? Why are we importing it here? What is the purpose of this tsx file?

2024-08-07 16:22 UTC, azizj1 requested changes
## High level comment

What is this web sample supposed to be? Have you even ran this demo? All of your configs are empty so I suspect this hasn't been ran locally. Do you have a video of you running this? Can you add it in the PR description?

## Comments regarding the code in PR

This sample is too complicated. Someone trying to understand add-ons will need to learn and setup firebase, know how nextjs works, and understand the benefits of tailwind. 

A couple of static pages via `webpack` is more than sufficient. No firebase, no nextjs, no tailwind.

2024-08-07 16:22 UTC, azizj1 commented on meet-addons-web-tutorial/src/meet/meet.d.ts
Why have this file checked in? It's already provided from the npm package

2024-08-16 04:37 UTC, sqrrrl commented on meet-addons-web-tutorial/src/meet/meet.d.ts
Disagree. Some context -- the tutorial was intended to be from the perspective of integrating an existing application. It should be a decent enough facsimile of a real app. Some complexity is OK as it's not necessary to understand the implementation in depth. Nobody has to be an expert in firebase or nextjs to complete the activity and it's standard in codelabs/tutorials to provide a starting app as context, particularly when it's about integrating a feature or capability.

Some simplification is OK and in order, but I'd caution about making it too trivial. If it's static and lacks any collaborative aspect it will fall flat. We're saying the value of Meet add-ons is to deliver multi-player, real time collaborative experiences in Meet, so at the end of the tutorial/codelab I expect to have accomplished at least something close to that.

2024-08-16 04:39 UTC, sqrrrl commented
> ## High level comment
> What is this web sample supposed to be? Have you even ran this demo? All of your configs are empty so I suspect this hasn't been ran locally. Do you have a video of you running this? Can you add it in the PR description?
> 
> ## Comments regarding the code in PR
> This sample is too complicated. Someone trying to understand add-ons will need to learn and setup firebase, know how nextjs works, and understand the benefits of tailwind.
> 
> A couple of static pages via `webpack` is more than sufficient. No firebase, no nextjs, no tailwind.

Disagree. Some context -- the tutorial was intended to be from the perspective of integrating an existing application. It should be a decent enough facsimile of a real app. Some complexity is OK as it's not necessary to understand the implementation in depth. Nobody has to be an expert in firebase or nextjs to complete the activity and it's standard in codelabs/tutorials to provide a starting app as context, particularly when it's about integrating a feature or capability.

Some simplification is OK and in order, but I'd caution about making it too trivial. If it's static and lacks *any* collaborative aspect it will fall flat. We're saying the value of Meet add-ons is to deliver multi-player, real time collaborative experiences in Meet, so at the end of the tutorial/codelab I expect to have accomplished at least something close to that.

2024-09-11 13:28 UTC, closed without merging